name: Verificar vuelos todos los días

# Se ejecuta según el cronograma definido en 'on'
on:
  schedule:
    - cron: '0 10 * * *'  # Se ejecuta todos los días a las 16:05 UTC
# Los trabajos que realiza el flujo de trabajo
jobs:
  run:
    runs-on: ubuntu-latest  # Utiliza un contenedor Ubuntu

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3  # Actualiza a la versión v3

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4  # Actualiza a la versión v4
        with:
          python-version: '3.x'  # Establece la versión de Python

      # 3. Instalar dependencias (si tienes un archivo 'requirements.txt')
      - name: Install dependencies
        run: |
          pip install -r .github/workflows/requirements.txt  # Instala las dependencias

      # 4. Ejecutar tu script
      - name: Run script
        run: |
          python Seguidor_vuelos/verificador_vuelos.py  # Ejecuta el script
